/**
 * PDF Executive Report Generator Engine
 * Generates printable executive health summaries with church branding and analytics.
 */

export interface PDFReportOptions {
  churchName: string
  logoUrl?: string
  date: string
  summary: string
  visitorsCount: number
  membersCount: number
  givingTotal: number
}

export function generateExecutiveReportPDF(options: PDFReportOptions): void {
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Executive Report — ${options.churchName}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #18181b; }
          .header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #6366f1; padding-bottom: 20px; margin-bottom: 30px; }
          .logo { height: 48px; object-fit: contain; }
          .title { font-size: 24px; font-weight: 800; color: #18181b; }
          .meta { font-size: 12px; color: #71717a; margin-top: 4px; }
          .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 30px; }
          .card { border: 1px solid #e4e4e7; border-radius: 12px; padding: 16px; background: #fafafa; }
          .card-title { font-size: 11px; color: #71717a; font-weight: 600; text-transform: uppercase; }
          .card-value { font-size: 20px; font-weight: 800; color: #6366f1; margin-top: 4px; }
          .section { border: 1px solid #e4e4e7; border-radius: 12px; padding: 20px; margin-bottom: 30px; }
          .section-title { font-size: 14px; font-weight: 700; margin-bottom: 12px; color: #18181b; }
          .content { font-size: 13px; line-height: 1.6; color: #3f3f46; white-space: pre-wrap; }
          .footer { border-top: 1px solid #e4e4e7; padding-top: 20px; font-size: 11px; text-align: center; color: #a1a1aa; }
          .footer a { color: #6366f1; text-decoration: none; font-weight: 600; }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="title">${options.churchName}</div>
            <div class="meta">Daily Executive Ministry Report • ${options.date}</div>
          </div>
          ${options.logoUrl ? `<img src="${options.logoUrl}" class="logo" />` : ''}
        </div>

        <div class="grid">
          <div class="card">
            <div class="card-title">Total Congregation</div>
            <div class="card-value">${options.membersCount}</div>
          </div>
          <div class="card">
            <div class="card-title">First-Time Visitors</div>
            <div class="card-value">${options.visitorsCount}</div>
          </div>
          <div class="card">
            <div class="card-title">Recorded Giving</div>
            <div class="card-value">₦${options.givingTotal.toLocaleString()}</div>
          </div>
        </div>

        <div class="section">
          <div class="section-title">🤖 AI Executive Summary</div>
          <div class="content">${options.summary}</div>
        </div>

        <div class="footer">
          Generated by <strong>Church Growth OS</strong> — A Product of <a href="https://mujteknify.com" target="_blank">MUJTEKNIFY LIMITED</a>
        </div>

        <script>
          window.onload = function() {
            window.print();
          }
        </script>
      </body>
    </html>
  `

  printWindow.document.write(html)
  printWindow.document.close()
}
